name: quick_ass_app
description: "Quick ASS App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope/Manrope-Regular.ttf
        - asset: fonts/Manrope/Manrope-Bold.ttf
          weight: 700
        - asset: fonts/Manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: fonts/Manrope/Manrope-Medium.ttf
          weight: 500
        - asset: fonts/Manrope/Manrope-Light.ttf
          weight: 300
        - asset: fonts/Manrope/Manrope-ExtraLight.ttf
          weight: 200

    - family: Instrument Serif
      fonts:
        - asset: fonts/InstrumentSerif/InstrumentSerif-Regular.ttf
        - asset: fonts/InstrumentSerif/InstrumentSerif-Italic.ttf
          style: italic

    - family: Space Mono
      fonts:
        - asset: fonts/SpaceMono/SpaceMono-Regular.ttf
        - asset: fonts/SpaceMono/SpaceMono-Italic.ttf
          style: italic
        - asset: fonts/SpaceMono/SpaceMono-Bold.ttf
          weight: 700
        - asset: fonts/SpaceMono/SpaceMono-BoldItalic.ttf
          weight: 700
          style: italic